Snehal Joshi

72030840C

23211

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

DSBDA Practical 1

**1. Importing libraries**

In [ ]:
import pandas as pd
import numpy as np

**2. and 3 Loading and Importing Dataset into Pandas dataframe**

In [ ]:
data= pd.read_csv("https://raw.githubusercontent.com/dphi-official/Datasets/master/abalone_data/training_set_label.csv")

**4 Preprocessing Data**

In [ ]:
data.head(10)

,Sex,Length,Diameter,Height,Whole weight,Shucked weight,Viscera weight,Shell weight,Rings
0,F,0.525,0.400,0.135,0.7140,0.3180,0.1380,0.2080,10
1,F,0.445,0.325,0.125,0.4550,0.1785,0.1125,0.1400,9
2,M,0.710,0.540,0.165,1.9590,0.7665,0.2610,0.7800,18
3,F,0.680,0.580,0.200,1.7870,0.5850,0.4530,0.6000,19
4,M,0.605,0.470,0.160,1.1735,0.4975,0.2405,0.3450,12
5,I,0.555,0.430,0.125,0.7005,0.3395,0.1355,0.2095,8
6,M,0.510,0.405,0.125,0.6925,0.3270,0.1550,0.1805,7
7,M,0.655,0.520,0.180,1.4920,0.7185,0.3600,0.3550,11
8,M,0.540,0.415,0.145,0.7400,0.2635,0.1680,0.2450,12
9,M,0.515,0.410,0.140,0.7355,0.3065,0.1370,0.2000,7

In [ ]:
data.tail(10)

,Sex,Length,Diameter,Height,Whole weight,Shucked weight,Viscera weight,Shell weight,Rings
3122,M,0.625,0.475,0.160,1.0845,0.5005,0.2355,0.3105,10
3123,M,0.660,0.515,0.155,1.4415,0.7055,0.3555,0.3350,10
3124,I,0.500,0.375,0.120,0.5420,0.2150,0.1160,0.1700,9
3125,F,0.620,0.485,0.165,1.1660,0.4830,0.2380,0.3550,13
3126,M,0.455,0.345,0.150,0.5795,0.1685,0.1250,0.2150,13
3127,M,0.415,0.315,0.120,0.4015,0.1990,0.0870,0.0970,8
3128,I,0.325,0.240,0.070,0.1520,0.0565,0.0305,0.0540,8
3129,M,0.565,0.455,0.155,0.9355,0.4210,0.1830,0.2600,11
3130,M,0.610,0.485,0.145,1.3305,0.7830,0.2255,0.2865,9
3131,F,0.655,0.505,0.190,1.3485,0.5935,0.2745,0.4250,12

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3132 entries, 0 to 3131
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Sex             3132 non-null   object
 1   Length          3132 non-null   float64
 2   Diameter        3132 non-null   float64
 3   Height          3132 non-null   float64
 4   Whole weight    3132 non-null   float64
 5   Shucked weight  3132 non-null   float64
 6   Viscera weight  3132 non-null   float64
 7   Shell weight    3132 non-null   float64
 8   Rings           3132 non-null   int64
dtypes: float64(7), int64(1), object(1)
memory usage: 220.3+ KB

In [ ]:
data.describe()

,Length,Diameter,Height,Whole weight,Shucked weight,Viscera weight,Shell weight,Rings
count,3132.000000,3132.000000,3132.000000,3132.00000,3132.000000,3132.000000,3132.000000,3132.000000
mean,0.523707,0.407952,0.139277,0.82867,0.359229,0.180731,0.239159,9.947957
std,0.119891,0.099336,0.038991,0.49063,0.221946,0.109924,0.139040,3.230252
min,0.110000,0.090000,0.000000,0.00800,0.002500,0.000500,0.003000,2.000000
25%,0.450000,0.350000,0.115000,0.44150,0.185375,0.093375,0.130000,8.000000
50%,0.545000,0.425000,0.140000,0.79950,0.335500,0.170000,0.235000,10.000000
75%,0.615000,0.480000,0.165000,1.15300,0.499500,0.252500,0.330000,11.000000
max,0.815000,0.650000,0.515000,2.82550,1.488000,0.760000,1.005000,29.000000

In [ ]:
data.isnull().sum()

Sex               0
Length            0
Diameter          0
Height            0
Whole weight      0
Shucked weight    0
Viscera weight    0
Shell weight      0
Rings             0
dtype: int64

In [ ]:
data.shape

(3132, 9)

**Categorical to Quantitative**

In [ ]:
abalone_data = pd.get_dummies(data, columns = ['Sex'])
print(abalone_data)

      Length  Diameter  Height  Whole weight  Shucked weight  Viscera weight  \
0      0.525     0.400   0.135        0.7140          0.3180          0.1380
1      0.445     0.325   0.125        0.4550          0.1785          0.1125
2      0.710     0.540   0.165        1.9590          0.7665          0.2610
3      0.680     0.580   0.200        1.7870          0.5850          0.4530
4      0.605     0.470   0.160        1.1735          0.4975          0.2405
...      ...       ...     ...           ...             ...             ...
3127   0.415     0.315   0.120        0.4015          0.1990          0.0870
3128   0.325     0.240   0.070        0.1520          0.0565          0.0305
3129   0.565     0.455   0.155        0.9355          0.4210          0.1830
3130   0.610     0.485   0.145        1.3305          0.7830          0.2255
3131   0.655     0.505   0.190        1.3485          0.5935          0.2745

      Shell weight  Rings  Sex_F  Sex_I  Sex_M
0           0.2080     10      1      0      0
1           0.1400      9      1      0      0
2           0.7800     18      0      0      1
3           0.6000     19      1      0      0
4           0.3450     12      0      0      1
...            ...    ...    ...    ...    ...
3127        0.0970      8      0      0      1
3128        0.0540      8      0      1      0
3129        0.2600     11      0      0      1
3130        0.2865      9      0      0      1
3131        0.4250     12      1      0      0

[3132 rows x 11 columns]

In [ ]:
abalone_data.describe()

,Length,Diameter,Height,Whole weight,Shucked weight,Viscera weight,Shell weight,Rings,Sex_F,Sex_I,Sex_M
count,3132.000000,3132.000000,3132.000000,3132.00000,3132.000000,3132.000000,3132.000000,3132.000000,3132.000000,3132.000000,3132.000000
mean,0.523707,0.407952,0.139277,0.82867,0.359229,0.180731,0.239159,9.947957,0.313218,0.323436,0.363346
std,0.119891,0.099336,0.038991,0.49063,0.221946,0.109924,0.139040,3.230252,0.463876,0.467862,0.481040
min,0.110000,0.090000,0.000000,0.00800,0.002500,0.000500,0.003000,2.000000,0.000000,0.000000,0.000000
25%,0.450000,0.350000,0.115000,0.44150,0.185375,0.093375,0.130000,8.000000,0.000000,0.000000,0.000000
50%,0.545000,0.425000,0.140000,0.79950,0.335500,0.170000,0.235000,10.000000,0.000000,0.000000,0.000000
75%,0.615000,0.480000,0.165000,1.15300,0.499500,0.252500,0.330000,11.000000,1.000000,1.000000,1.000000
max,0.815000,0.650000,0.515000,2.82550,1.488000,0.760000,1.005000,29.000000,1.000000,1.000000,1.000000