Snehal Joshi 
<br>
72030840C<br>
23211<br>

**Practical 3.2**<br>
Write a Python program to display some basic statistical details like percentile, mean,
standard deviation etc. of the species of ‘Iris-setosa’, ‘Iris-versicolor’ and ‘Irisversicolor’ of iris.csv dataset

In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
data =pd.read_csv("/content/drive/MyDrive/DSBDA/Datasets/Iris.csv")

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [ ]:
data.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [ ]:
data.shape

(150, 6)

In [ ]:
data.size

900

**Statistical Summary of the dataset**

In [ ]:
data.min()

Id                         1
SepalLengthCm            4.3
SepalWidthCm             2.0
PetalLengthCm            1.0
PetalWidthCm             0.1
Species          Iris-setosa
dtype: object

In [ ]:
data.max()

Id                          150
SepalLengthCm               7.9
SepalWidthCm                4.4
PetalLengthCm               6.9
PetalWidthCm                2.5
Species          Iris-virginica
dtype: object

In [ ]:
df = data.drop(['Species'], axis = 1)

In [ ]:
df.mean()

Id               75.500000
SepalLengthCm     5.843333
SepalWidthCm      3.054000
PetalLengthCm     3.758667
PetalWidthCm      1.198667
dtype: float64

In [ ]:
df.mode()

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0      1            5.0           3.0            1.5           0.2
1      2            NaN           NaN            NaN           NaN
2      3            NaN           NaN            NaN           NaN
3      4            NaN           NaN            NaN           NaN
4      5            NaN           NaN            NaN           NaN
..   ...            ...           ...            ...           ...
145  146            NaN           NaN            NaN           NaN
146  147            NaN           NaN            NaN           NaN
147  148            NaN           NaN            NaN           NaN
148  149            NaN           NaN            NaN           NaN
149  150            NaN           NaN            NaN           NaN

[150 rows x 5 columns]

In [ ]:
df.median()

Id               75.50
SepalLengthCm     5.80
SepalWidthCm      3.00
PetalLengthCm     4.35
PetalWidthCm      1.30
dtype: float64

In [ ]:
df.std()

Id               43.445368
SepalLengthCm     0.828066
SepalWidthCm      0.433594
PetalLengthCm     1.764420
PetalWidthCm      0.763161
dtype: float64

**Summary statistics for Data after grouped by categorical variable (Result)**

In [ ]:
data1 = data.groupby('Species').describe()

While describing the Marks dataset horizontally, all the columns were not fitting in the screen. That is why I have used transpose of the dataset

In [ ]:
data1.transpose()

Species              Iris-setosa  Iris-versicolor  Iris-virginica
Id            count    50.000000        50.000000       50.000000
              mean     25.500000        75.500000      125.500000
              std      14.577380        14.577380       14.577380
              min       1.000000        51.000000      101.000000
              25%      13.250000        63.250000      113.250000
              50%      25.500000        75.500000      125.500000
              75%      37.750000        87.750000      137.750000
              max      50.000000       100.000000      150.000000
SepalLengthCm count    50.000000        50.000000       50.000000
              mean      5.006000         5.936000        6.588000
              std       0.352490         0.516171        0.635880
              min       4.300000         4.900000        4.900000
              25%       4.800000         5.600000        6.225000
              50%       5.000000         5.900000        6.500000
              75%       5.200000         6.300000        6.900000
              max       5.800000         7.000000        7.900000
SepalWidthCm  count    50.000000        50.000000       50.000000
              mean      3.418000         2.770000        2.974000
              std       0.381024         0.313798        0.322497
              min       2.300000         2.000000        2.200000
              25%       3.125000         2.525000        2.800000
              50%       3.400000         2.800000        3.000000
              75%       3.675000         3.000000        3.175000
              max       4.400000         3.400000        3.800000
PetalLengthCm count    50.000000        50.000000       50.000000
              mean      1.464000         4.260000        5.552000
              std       0.173511         0.469911        0.551895
              min       1.000000         3.000000        4.500000
              25%       1.400000         4.000000        5.100000
              50%       1.500000         4.350000        5.550000
              75%       1.575000         4.600000        5.875000
              max       1.900000         5.100000        6.900000
PetalWidthCm  count    50.000000        50.000000       50.000000
              mean      0.244000         1.326000        2.026000
              std       0.107210         0.197753        0.274650
              min       0.100000         1.000000        1.400000
              25%       0.200000         1.200000        1.800000
              50%       0.200000         1.300000        2.000000
              75%       0.300000         1.500000        2.300000
              max       0.600000         1.800000        2.500000